[package]
name = "aoc_module_loader"
version = "0.0.1"
authors = ["Tom Udding <tomudding@users.noreply.github.com>"]
edition = "2021"

[dependencies]
syn = { version = "2.0.90", features = ["full"] }
quote = "1.0.37"
proc-macro2 = "1.0.92"

[lib]
proc-macro = true
